// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "dev.kanka.voice-notes",
  "name": "Voice Notes",
  "description": "Record and share voice messages directly in Mattermost channels.",
  "homepage_url": "https://github.com/kanka-dev/mattermost-plugin-voice-notes",
  "support_url": "https://github.com/kanka-dev/mattermost-plugin-voice-notes/issues",
  "icon_path": "assets/icon.svg",
  "version": "1.0.0",
  "min_server_version": "10.0.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Configure the Voice Notes plugin behaviour.",
    "footer": "",
    "settings": [
      {
        "key": "MaxDurationSeconds",
        "display_name": "Max Recording Duration (seconds)",
        "type": "number",
        "help_text": "Maximum allowed duration for a single voice note recording. Default is 300 seconds (5 minutes).",
        "placeholder": "",
        "default": 300,
        "hosting": "",
        "secret": false
      },
      {
        "key": "MaxFileSizeMB",
        "display_name": "Max File Size (MB)",
        "type": "number",
        "help_text": "Maximum allowed file size for a voice note upload. Default is 50 MB.",
        "placeholder": "",
        "default": 50,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
